Repository gisce/cchloader, pull requests merged in 2024-12, with the labels that each got.

#48 Pasar a coma flotante las magnitudes del fichero CORBAGEN
  cchloader/adapters/corbagen.py
  cchloader/models/corbagen.py
  spec/curve_files/CORBAGEN_202403.0
  spec/test_parsers_spec.py
Labels: enhancement, WIP

#52 Correcciones en el formato de los ficheros reganecuQH
  cchloader/parsers/reganecuqh.py
  spec/curve_files/C3_reganecuQH_20240501_demo
  spec/test_parsers_spec.py
Labels: bug

#54 FIX P1 addapter
  cchloader/adapters/p1.py
Labels: bug, to be merged
