Repository gisce/cchloader, pull requests merged in 2024-04, with the labels that each got.

#41 PY3 compat
  cchloader/adapters/a5d.py
  cchloader/adapters/b5d.py
  cchloader/adapters/corbagen.py
  cchloader/adapters/f1.py
  cchloader/adapters/f5d.py
  cchloader/adapters/infpa.py
  cchloader/adapters/medidas.py
  cchloader/adapters/mhcil.py
  cchloader/adapters/p1.py
  cchloader/adapters/p5d.py
  cchloader/adapters/reganecu.py
  cchloader/compress.py
  cchloader/file.py
  cchloader/parsers/a5d.py
  cchloader/parsers/b5d.py
  cchloader/parsers/corbagen.py
  cchloader/parsers/f1.py
  cchloader/parsers/f5d.py
  cchloader/parsers/infpa.py
  cchloader/parsers/medidas.py
  cchloader/parsers/mhcil.py
  cchloader/parsers/p1.py
  cchloader/parsers/p1d.py
  cchloader/parsers/p2.py
  cchloader/parsers/p2d.py
  cchloader/parsers/p5d.py
  cchloader/parsers/reganecu.py
  requirements-dev.txt
  requirements.txt
Labels: enhancement, help wanted, deployed

#43 FIX Detección de fichero comprimido en python2
  cchloader/compress.py
Labels: bug

#44 Fix cast to int when value is None
  cchloader/adapters/p1.py
Labels: bug, to be merged
